# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b19743d1e8a6ed4f528bd4416939b3b2cfdd40fb0450e4c103b81beb9a9381920d463ebf8b5eb8c0443ae584558c34220c556fa9c769df9b263aca540a501aa

test:
  secret_key_base: 3c892a07b7691e9835be89f943e08c19a3ef6dce9f330e6ffe61385d782def845aa2546b8f81eb4e486399a00a0dbb38053a21e661a09c1d271ba2e25353e30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
